# Generated by Django 4.0.4 on 2022-04-28 09:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_type', models.CharField(choices=[('ord', 'order'), ('cons', 'consultation')], max_length=5)),
            ],
            options={
                'verbose_name': 'Типы заявок',
                'db_table': 'Типы заявок',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Контактное лицо')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Контакты',
                'db_table': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_birth', models.DateField(default=None, null=True)),
                ('work_experience', models.DateField(default=None, null=True)),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастеры',
                'db_table': 'Мастеры',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=500)),
                ('works_price', models.FloatField()),
                ('description', models.TextField(max_length=2000, verbose_name='Краткое описание работы')),
                ('works_photo', models.ImageField(upload_to='', verbose_name='Фото работы')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'db_table': 'Наши работы',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('works_title', models.CharField(max_length=1000)),
                ('works_price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'db_table': 'Прайс-лист',
            },
        ),
        migrations.AlterModelOptions(
            name='applications',
            options={'verbose_name': 'Заявки'},
        ),
        migrations.AlterModelTable(
            name='applications',
            table='Заявки',
        ),
        migrations.AlterField(
            model_name='applications',
            name='applications_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santech.applicationstypes'),
        ),
        migrations.DeleteModel(
            name='AplicationsTypes',
        ),
    ]
