# Generated by Django 4.0.4 on 2022-04-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0002_applicationstypes_contacts_masters_ourwork_pricelist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstypes',
            options={'verbose_name': 'Типы заявок', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AlterField(
            model_name='applicationstypes',
            name='applications_type',
            field=models.CharField(choices=[('ord', 'заказ'), ('cons', 'консультация')], max_length=5, verbose_name='Типы заявок'),
        ),
        migrations.RenameModel(
            old_name='OurWork',
            new_name='OurWorks',
        ),
        migrations.CreateModel(
            name='FilesForWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d')),
                ('for_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santech.ourworks')),
            ],
            options={
                'db_table': 'Файлы для работ',
            },
        ),
    ]
