# Generated by Django 4.0.4 on 2022-04-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0003_alter_applicationstypes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstypes',
            name='applications_type',
            field=models.CharField(choices=[('заказ', 'заказ'), ('консультация', 'консультация')], max_length=12, verbose_name='Типы заявок'),
        ),
    ]
