# Generated by Django 4.0.4 on 2022-05-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0005_remove_masters_date_birth_masters_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourworks',
            old_name='work_title',
            new_name='works_title',
        ),
    ]
