# Generated by Django 4.0.4 on 2022-05-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0007_alter_ourworks_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс-лист', 'verbose_name_plural': 'Прайс-листы'},
        ),
    ]
