# Generated by Django 4.0.4 on 2022-05-02 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0008_alter_pricelist_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoForWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='files_works/%Y/%m/%d')),
                ('for_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='santech.ourworks')),
            ],
            options={
                'db_table': 'Фото работ',
            },
        ),
        migrations.DeleteModel(
            name='FilesForWorks',
        ),
    ]
