# Generated by Django 4.0.4 on 2022-05-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santech', '0009_photoforworks_delete_filesforworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourworks',
            name='works_price',
            field=models.FloatField(verbose_name='Цена работы'),
        ),
        migrations.AlterField(
            model_name='ourworks',
            name='works_title',
            field=models.CharField(max_length=500, verbose_name='Название работы'),
        ),
        migrations.AlterField(
            model_name='photoforworks',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='files_works/%Y/%m/%d', verbose_name='Фото работы'),
        ),
    ]
